export const plans = [
  {
    id: 1,
    name: 'Anual',
    big_price: 14,
    little_price: ',90/mês',
    text_discount: 'Economize R$ 120,00 no final do ano com nosso plano mais em conta',
    text_installments: 'Parcele em até 12x de R$ 9,90 sem juros ou 1x de R$ 178,80',
    description: '*renovação autimatica a cada 12 meses',
    big_square_color: '#F9A491',
    little_square_color: '#A62F27',
  },
  {
    id: 2,
    name: 'Semestral',
    big_price: 19,
    little_price: ',90/mês',
    text_discount: 'Economize R$ 60,00 no final do ano com nosso plano mais em conta',
    text_installments: 'Parcele em até 6x de R$ 14,90 sem júros ou 1x de R$ 238,80',
    description: '*renovação autimatica a cada 6 mês',
    big_square_color: '#A3DD94',
    little_square_color: '#27A62C',
  },
  {
    id: 3,
    name: 'Mensal',
    big_price: 24,
    little_price: ',90/mês',
    text_discount: 'Teste todo seu potêncial durante um mês com o nosso plano mensal.',
    text_installments: 'Compre em 1 x de 24,90',
    description: '*renovação autimatica a cada mês',
    big_square_color: '#DEA7BE',
    little_square_color: '#D33D7C',
  },
];
